# Generated by Django 4.2 on 2023-05-13 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Othes')], default='choose one', max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('licensenum', models.CharField(max_length=30)),
                ('hospital', models.CharField(max_length=50)),
                ('speciality', models.TextField(max_length=100)),
                ('qualification', models.TextField(max_length=100)),
                ('availability', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('fees', models.CharField(max_length=5)),
                ('profilepic', models.FileField(upload_to='')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('policy', models.TextField()),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('blood', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Othes')], default='choose one', max_length=10)),
                ('medications', models.TextField()),
                ('disease', models.TextField()),
                ('allergy', models.TextField()),
                ('profilepic', models.FileField(upload_to='')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.insuranceprovider')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('hospital', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='prescription/')),
                ('presctext', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.patient')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
