# Generated by Django 4.2 on 2023-05-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.insuranceprovider'),
        ),
    ]
