# Generated by Django 4.2 on 2023-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0002_alter_patient_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
