# Generated by Django 4.2 on 2023-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0003_alter_patient_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
