# Generated by Django 4.2 on 2023-05-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0004_alter_prescription_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('disease', models.TextField(blank=True)),
                ('expected_date', models.DateField()),
                ('expected_time', models.TimeField()),
                ('requested_at', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.patient')),
            ],
        ),
    ]
