# Generated by Django 4.2 on 2023-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0006_appointment_doctor_name_appointment_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start',
            field=models.TimeField(),
        ),
    ]
