# Generated by Django 4.2 on 2023-05-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0008_buddy_alter_doctor_profilepic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddy',
            name='user',
        ),
        migrations.AddField(
            model_name='buddy',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.profile'),
            preserve_default=False,
        ),
    ]
