# Generated by Django 4.2 on 2023-10-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0010_remove_chat_msg_receiver_remove_chat_msg_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.CharField(choices=[('On-Site', 'On-Site'), ('Online', 'Online'), ('online', 'online'), ('on-site', 'on-site')], default='choose one', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='percentage',
            field=models.CharField(default='5', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('male', 'male'), ('female', 'female'), ('Others', 'Othes')], default='choose one', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('male', 'male'), ('female', 'female'), ('Others', 'Othes')], default='choose one', max_length=10),
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_num', models.CharField(blank=True, default=0, max_length=10)),
                ('comission', models.CharField(blank=True, max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.doctor')),
            ],
        ),
    ]
