# Generated by Django 4.2 on 2023-10-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0011_appointment_payment_doctor_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comission',
            old_name='comission',
            new_name='total_earnings',
        ),
    ]
