# Generated by Django 4.2 on 2023-10-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0012_rename_comission_comission_total_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mediaid_app.doctor'),
        ),
    ]
