# Generated by Django 4.2 on 2023-10-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0013_alter_comission_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='patient_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comission',
            name='total_earnings',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
