# Generated by Django 4.2 on 2023-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0014_alter_comission_patient_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.CharField(choices=[('On-Site', 'On-Site'), ('Online', 'Online'), ('online', 'online'), ('on-site', 'on-site')], default='On-Site', max_length=10),
        ),
    ]
